build:
  stage: build
  image: node:16.13.2
  only:
    - dev
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  only:
    - dev
  image: python:latest
  dependencies:
    - build
  script:
    - pip install awscli
    - aws s3 cp build/ s3://$S3_BUCKET/ --recursive --include "*" 
